{extends file="admin_base.tpl"}

{block name=headers}

<style type="text/css">
.nextButton {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#777777;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.nextButton:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.nextButton:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>

<script>

$(document).ready(function(){

$('input[type=text],textarea').focus(function() {
	$(this).toggleClass("highlight").fadeIn(250);
});
$('input[type=text]input,textarea').blur(function() {
	$(this).toggleClass("highlight");
});

// $('.formwizard').toggle();
// $('#first').toggle();

} );

</script>


{/block}

{block name=body}
<div class="entry">
	
	<form action="uploadadvert.php" method="post" enctype="multipart/form-data">
	<input type="hidden" name="token" value="{$token}" />
	<h2>Add sponsor</h2>
	<div class="text">
		This for is for adding sponsor logos to the random rotation. Before completing this form
		please ensure that the logos the sponsor has supplied conform to the file dimensions for
		the advertising space(s) the sponsor has provided logos for. These sizes are (all sizes
		are quoted as width x height):
		<ul>
			<li><strong>Bronze</strong>: 234 x 60 pixels </li>
			<li><strong>Silver</strong>: 160 x 600 pixels. <strong>Note</strong> This is a skyscraper advert size.</li>
			<li><strong>Gold</strong>: 468 x 66 pixels</li>
			<li><strong>Ticker</strong>: 150 x 50 pixels. <strong>Note</strong> Images for the ticker should ideally be .png files with a transparent background</li>
		</ul>


	</div>

	{* 
		The following will be added if a sanity check has been asked for by the PHP. This should
		normally be done whenever the SQL is changed, because it's far better to check first than
		untangle the mess later.
	 *}
	{if isset($sanity_check)}
		<div class="admin_warning">
			{$sanity_check}
		</div>

	{/if}
		<fieldset>
			<legend>Click-through information</legend>
			<div>The following information is required for all sponsors.</div>
			<div>The Sponsor is the name of the sponsor as they are known to us. This would normally be their trading name, but this is not necessarialy so. This is used for internal purposes to ensure that we know which traders and sponsors have logos, and which are missing.</div>
			<div>The URL is the location the sponsor wishes the user to visit if their logo is clicked. If no specific url has been given by the sponsor, a link to their home page should normally be given</div>
			<div>The Alt-text/hover-text field is what is displayed when the user hovers over their image. Unless otherwise specified, this will normally be their name</div>
			{if isset($sponsor_error)}
			<div class="admin_warning">
				{$sponsor_error}
			</div>
			{/if}
			<div><label>Sponsor</label><input type="text" name="sponsorname" placeholder="Name of sponsor" /></div>

			<div><label>Url</label><input type="text" name="url" placeholder="Click-through URL"/></div>
			<div><label>Alt-text / hover-text</label><input type="text" name="alttext" id="alttext" placeholder="Text when user hovers"/></div>
		</fieldset>
	
		<div class="text">
			Select the images for each of <strong>Ticker</strong>, <strong>Gold</strong>, <strong>Silver</strong> and <strong>Bronze</strong> adverts for which the sponsor has provided images. If no image has been provided for a given advertising category, or the sponsor has not elected to provide an image for a category, simply ignore that section.
		</div>

		<fieldset>
			<legend>Ticker image</legend>
			<div class="description">
				The <strong>ticker</strong> image is the image that is shown in the
				'ticker-tape' on every page on the main banner. The ticker image <strong>
				must</strong> be 150x50 pixels (width x height) and <strong>should</strong>
				be a .PNG with a transparent background to maintain consistency. 
			</div>
			{if isset($fileErrors.ticker_file_error)}
			<div class="admin_warning">
				<strong>An error occured uploading this file</strong>
				<p>{$fileErrors.ticker_file_error}</p>
			</div>
			{/if}
			<div><label>Select file</label><input type="file" name="ticker_file" id="ticker_file" /></div>
		</fieldset>
		<fieldset>
			<legend>BRONZE Image</legend>		
			<div class="description">
				A Bronze sponsor <strong>must</strong> be 234 x 60 pixel (width x height).
				This is the standard Half Banner size. 
			</div>
			{if isset($fileErrors.bronze_file_error)}
			<div class="admin_warning">
				<strong>An error occured uploading this file</strong>
				<p>{$fileErrors.bronze_file_error}</p>
			</div>
			{/if}
			<div><label>Select file</label><input type="file" name="bronze_file" id="bronze_file" placeholder="Bronze banner image" /></div>
		</fieldset>
		<fieldset>
			<legend>SILVER Image</legend>		
			<div class="description">
				A silver 
				sponsor <strong>must</strong> be 160x600 pixels (width x height).
				This is the standard Wide Skyscraper size.
			</div>
			{if isset($fileErrors.silver_file_error)}
			<div class="admin_warning">
				<strong>An error occured uploading this file</strong>
				<p>{$fileErrors.silver_file_error}</p>
			</div>
			{/if}
			<div><label>Select file</label><input type="file" name="silver_file" id="silver_file" placeholder="Silver banner image" /></div>
		</fieldset>
		<fieldset>
			<legend>GOLD Image</legend>
			<div class="description">
				A gold sponsor <strong>must</strong> be 468x66 pixels (width x height).
			</div>
			{if isset($fileErrors.gold_file_error)}
			<div class="admin_warning">
				<strong>An error occured uploading this file</strong>
				<p>{$fileErrors.gold_file_error}</p>
			</div>
			{/if}
			<div><label>Select file</label><input type="file" name="gold_file" id="gold_file" placeholder="Gold banner image" /></div>
			<div><input type="submit" /></div>
		</fieldset>
	</form>
</div>
{/block}